import { NoCProject } from '../types/noc';

/**
 * Generates an executable gem5 Python configuration script for Garnet NoC.
 * Includes custom template blocks at the top as requested.
 */
export function generateGem5PythonScript(project: NoCProject): string {
  const lines: string[] = [];

  // 1. Header Information
  lines.push(`# ==============================================================================`);
  lines.push(`# gem5 Garnet NoC Topology & System Configuration`);
  lines.push(`# Generated by Garnet NoC Visual Editor`);
  lines.push(`# Topology Name: ${project.name}`);
  lines.push(`# Created: ${project.created}`);
  lines.push(`# Modified: ${project.modified}`);
  lines.push(`# ==============================================================================`);
  lines.push(``);
  lines.push(`import m5`);
  lines.push(`from m5.objects import *`);
  lines.push(`from m5.defines import buildEnv`);
  lines.push(`from m5.objects.Topology import BaseTopology`);
  lines.push(``);

  // 2. Custom Template Definitions Section (At the top of the file as requested)
  lines.push(`# ==============================================================================`);
  lines.push(`# SECTION 1: CUSTOM TEMPLATE DEFINITIONS & COMPLEX COMPONENT TYPES`);
  lines.push(`# Modify the classes below to integrate user-defined C++/Python gem5 objects`);
  lines.push(`# ==============================================================================`);
  lines.push(``);

  let hasCustomTemplates = false;

  // Global custom templates
  if (project.globalTemplates && project.globalTemplates.length > 0) {
    project.globalTemplates.forEach((template) => {
      if (template.enabled && template.code.trim().length > 0) {
        hasCustomTemplates = true;
        lines.push(`# --- Global Template: ${template.name} ---`);
        lines.push(template.code.trim());
        lines.push(``);
      }
    });
  }

  // Node-level custom templates
  project.nodes.forEach((node) => {
    if (node.data.type === 'template' && node.data.templateClassCode?.trim()) {
      hasCustomTemplates = true;
      lines.push(`# --- Node Template Class: ${node.data.label} (ID: ${node.id}) ---`);
      lines.push(node.data.templateClassCode.trim());
      lines.push(``);
    }
  });

  if (!hasCustomTemplates) {
    lines.push(`# Default Custom Node Template Placeholder`);
    lines.push(`class CustomGarnetAccelerator(ClockedObject):`);
    lines.push(`    type = 'CustomGarnetAccelerator'`);
    lines.push(`    cxx_header = "mem/ruby/structures/CustomGarnetAccelerator.hh"`);
    lines.push(`    cxx_class = "gem5::ruby::CustomGarnetAccelerator"`);
    lines.push(`    processing_delay = Param.Cycles(1, "Processing latency in cycles")`);
    lines.push(``);
  }

  // 3. Garnet Topology Definition Class
  lines.push(`# ==============================================================================`);
  lines.push(`# SECTION 2: GARNET NOC TOPOLOGY DEFINITION`);
  lines.push(`# ==============================================================================`);
  lines.push(``);
  lines.push(`class Garnet${sanitizeClassName(project.name)}Topology(BaseTopology):`);
  lines.push(`    """`);
  lines.push(`    Autogenerated Garnet NoC Topology Class.`);
  lines.push(`    Contains ${project.nodes.filter(n => n.data.type === 'router').length} Routers and ${project.nodes.filter(n => n.data.type !== 'router').length} Endpoints.`);
  lines.push(`    """`);
  lines.push(`    def __init__(self, controllers):`);
  lines.push(`        super().__init__(controllers)`);
  lines.push(``);
  lines.push(`    def makeTopology(self, options, network, IntLink, ExtLink, Router):`);
  lines.push(`        nodes = self.nodes`);
  lines.push(``);

  // Map nodes
  const routerNodes = project.nodes.filter((n) => n.data.type === 'router');
  const endpointNodes = project.nodes.filter((n) => n.data.type !== 'router');

  // Assign router IDs sequentially if not set
  const routerIdMap = new Map<string, number>();
  routerNodes.forEach((node, index) => {
    const rId = node.data.routerId !== undefined ? node.data.routerId : index;
    routerIdMap.set(node.id, rId);
  });

  // Instantiate Routers
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        # Instantiate NoC Routers`);
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        routers = []`);
  routerNodes.forEach((rNode) => {
    const rId = routerIdMap.get(rNode.id);
    const latency = rNode.data.latency || 1;
    lines.push(`        routers.append(Router(router_id=${rId}, latency=${latency}))  # Node: ${rNode.data.label}`);
  });
  lines.push(`        network.routers = routers`);
  lines.push(``);

  // Internal Links (Router -> Router)
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        # Internal Links (Router to Router)`);
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        int_links = []`);
  let linkCounter = 0;

  project.links.forEach((link) => {
    const srcIsRouter = routerIdMap.has(link.source);
    const dstIsRouter = routerIdMap.has(link.target);

    if (srcIsRouter && dstIsRouter) {
      const srcRouterId = routerIdMap.get(link.source);
      const dstRouterId = routerIdMap.get(link.target);
      const latency = link.latency || 1;
      const weight = link.weight || 1;
      const bwBytes = Math.max(1, Math.floor((link.bandwidth || 128) / 8));

      // Forward link
      lines.push(
        `        int_links.append(IntLink(link_id=${linkCounter++}, src_node=routers[${srcRouterId}], dst_node=routers[${dstRouterId}], latency=${latency}, weight=${weight}, width=${bwBytes}))`
      );

      // Bidirectional link
      if (link.direction === 'bi') {
        lines.push(
          `        int_links.append(IntLink(link_id=${linkCounter++}, src_node=routers[${dstRouterId}], dst_node=routers[${srcRouterId}], latency=${latency}, weight=${weight}, width=${bwBytes}))`
        );
      }
    }
  });

  lines.push(`        network.int_links = int_links`);
  lines.push(``);

  // External Links (Endpoints -> Routers)
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        # External Links (Endpoints & Controllers to Routers)`);
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        ext_links = []`);
  let extLinkCounter = 0;

  endpointNodes.forEach((epNode, idx) => {
    // Find router connected to this endpoint
    const connectedLink = project.links.find(
      (l) => (l.source === epNode.id && routerIdMap.has(l.target)) || (l.target === epNode.id && routerIdMap.has(l.source))
    );

    const routerId = connectedLink
      ? routerIdMap.get(connectedLink.source === epNode.id ? connectedLink.target : connectedLink.source)
      : 0;

    const compType = epNode.data.gem5Component || 'CPU_Timing';
    const label = epNode.data.label || `Endpoint_${idx}`;
    const latency = connectedLink ? connectedLink.latency : 1;
    const bwBytes = connectedLink ? Math.max(1, Math.floor((connectedLink.bandwidth || 128) / 8)) : 16;

    if (epNode.data.type === 'template') {
      // Template custom endpoint
      lines.push(`        # Custom Template Endpoint: ${label}`);
      if (epNode.data.templateInstantiationCode?.trim()) {
        lines.push(`        # User Instantiation:`);
        lines.push(`        # ${epNode.data.templateInstantiationCode.trim().replace(/\n/g, '\n        # ')}`);
      }
      lines.push(
        `        if len(nodes) > ${idx}:`
      );
      lines.push(
        `            ext_links.append(ExtLink(link_id=${extLinkCounter++}, extnode=nodes[${idx}], intnode=routers[${routerId}], latency=${latency}, width=${bwBytes}))`
      );
    } else {
      // Standard gem5 component type
      lines.push(`        # ${compType} Component (${label}) connected to Router ${routerId}`);
      lines.push(
        `        if len(nodes) > ${idx}:`
      );
      lines.push(
        `            ext_links.append(ExtLink(link_id=${extLinkCounter++}, extnode=nodes[${idx}], intnode=routers[${routerId}], latency=${latency}, width=${bwBytes}))`
      );
    }
  });

  lines.push(`        network.ext_links = ext_links`);
  lines.push(``);

  // 4. Standalone Runner & Network Configuration Helper
  lines.push(`# ==============================================================================`);
  lines.push(`# SECTION 3: SYSTEM INTEGRATION & RUNNER UTILITY`);
  lines.push(`# ==============================================================================`);
  lines.push(``);
  lines.push(`def create_garnet_network(ruby_system, controllers):`);
  lines.push(`    """`);
  lines.push(`    Helper function to instantiate and register GarnetNetwork into a Ruby System`);
  lines.push(`    """`);
  lines.push(`    network = GarnetNetwork(`);
  lines.push(`        ruby_system=ruby_system,`);
  lines.push(`        vcs_per_vnet=${project.settings.buffersPerVC || 4},`);
  lines.push(`        buffers_per_data_vc=${project.settings.buffersPerVC || 4},`);
  lines.push(`        buffers_per_ctrl_vc=${project.settings.buffersPerVC || 4},`);
  lines.push(`        ni_single_vnet_buffer=${project.settings.niSingleVnetBuffer ? 'True' : 'False'},`);
  lines.push(`        routing_algorithm=${project.settings.routingAlgorithm === 'xy' ? 1 : 0}`);
  lines.push(`    )`);
  lines.push(`    topology = Garnet${sanitizeClassName(project.name)}Topology(controllers)`);
  lines.push(`    topology.makeTopology(None, network, IntLink, ExtLink, Router)`);
  lines.push(`    return network`);
  lines.push(``);

  lines.push(`# Standard execution entry point`);
  lines.push(`if __name__ == '__main__':`);
  lines.push(`    print("Garnet NoC Topology: ${project.name}")`);
  lines.push(`    print("Routers: ${routerNodes.length}, Endpoints: ${endpointNodes.length}, Links: ${project.links.length}")`);

  return lines.join('\n');
}

function sanitizeClassName(str: string): string {
  return str.replace(/[^a-zA-Z0-9]/g, '');
}
