import { NoCProject, Gem5ComponentType } from '../types/noc';

/**
 * Generates an executable gem5 Python configuration script for Garnet NoC.
 * Includes factory helper methods for repeated component types (>1 instances),
 * direct inline instantiation for single instances (==1 instance),
 * global workload binary path execution, and gem5 port setup.
 */
export function generateGem5PythonScript(project: NoCProject): string {
  const lines: string[] = [];
  const binaryPath = project.settings.binaryPath?.trim();

  // 1. Header Information
  lines.push(`# ==============================================================================`);
  lines.push(`# gem5 Garnet NoC Topology & System Configuration`);
  lines.push(`# Generated by Garnet NoC Visual Editor`);
  lines.push(`# Topology Name: ${project.name}`);
  lines.push(`# Created: ${project.created}`);
  lines.push(`# Modified: ${project.modified}`);
  lines.push(`# ==============================================================================`);
  lines.push(``);
  lines.push(`import m5`);
  lines.push(`from m5.objects import *`);
  lines.push(`from m5.defines import buildEnv`);
  lines.push(`from m5.objects.Topology import BaseTopology`);
  lines.push(``);

  // 2. Custom Template Definitions Section
  lines.push(`# ==============================================================================`);
  lines.push(`# SECTION 1: CUSTOM TEMPLATE DEFINITIONS & COMPLEX COMPONENT TYPES`);
  lines.push(`# Modify the classes below to integrate user-defined C++/Python gem5 objects`);
  lines.push(`# ==============================================================================`);
  lines.push(``);

  let hasCustomTemplates = false;

  // Global custom templates
  if (project.globalTemplates && project.globalTemplates.length > 0) {
    project.globalTemplates.forEach((template) => {
      if (template.enabled && template.code.trim().length > 0) {
        hasCustomTemplates = true;
        lines.push(`# --- Global Template: ${template.name} ---`);
        lines.push(template.code.trim());
        lines.push(``);
      }
    });
  }

  // Node-level custom templates
  project.nodes.forEach((node) => {
    if (node.data.type === 'template' && node.data.templateClassCode?.trim()) {
      hasCustomTemplates = true;
      lines.push(`# --- Node Template Class: ${node.data.label} (ID: ${node.id}) ---`);
      lines.push(node.data.templateClassCode.trim());
      lines.push(``);
    }
  });

  if (!hasCustomTemplates) {
    lines.push(`# Default Custom Node Template Placeholder`);
    lines.push(`class CustomGarnetAccelerator(ClockedObject):`);
    lines.push(`    type = 'CustomGarnetAccelerator'`);
    lines.push(`    cxx_header = "mem/ruby/structures/CustomGarnetAccelerator.hh"`);
    lines.push(`    cxx_class = "gem5::ruby::CustomGarnetAccelerator"`);
    lines.push(`    processing_delay = Param.Cycles(1, "Processing latency in cycles")`);
    lines.push(``);
  }

  // 3. Count frequency of each component type across all endpoint nodes
  const routerNodes = project.nodes.filter((n) => n.data.type === 'router');
  const endpointNodes = project.nodes.filter((n) => n.data.type !== 'router');

  const typeCounts = new Map<string, number>();
  endpointNodes.forEach((node) => {
    const key = node.data.type === 'template'
      ? (node.data.label ? sanitizeVarName(node.data.label) : 'custom_template')
      : (node.data.gem5Component || 'CPU_Timing');
    typeCounts.set(key, (typeCounts.get(key) || 0) + 1);
  });

  // 4. Section 2: Factory Helper Functions (Only for component types used MORE THAN ONCE (>1))
  lines.push(`# ==============================================================================`);
  lines.push(`# SECTION 2: FACTORY HELPER METHODS & COMPONENT BUILDERS`);
  lines.push(`# Factory functions are generated ONLY for component types used > 1 time.`);
  lines.push(`# ==============================================================================`);
  lines.push(``);

  const generatedHelpers = new Set<string>();

  typeCounts.forEach((count, typeKey) => {
    if (count > 1) {
      generatedHelpers.add(typeKey);
      lines.push(`# --- Factory Helper Method for repeated type: ${typeKey} (Used ${count}x) ---`);

      if (typeKey === 'CPU_Timing') {
        lines.push(`def create_cpu_timing_helper(system, cpu_id, binary_path=None):`);
        lines.push(`    """Compute Tile: TimingSimpleCPU + Sequencer + Ruby L1Cache_Controller"""`);
        lines.push(`    cpu = TimingSimpleCPU(cpu_id=cpu_id)`);
        lines.push(`    cpu.createInterruptController()`);
        lines.push(`    if binary_path:`);
        lines.push(`        process = Process(cmd=[binary_path])`);
        lines.push(`        cpu.workload = process`);
        lines.push(`        cpu.createThreads()`);
        lines.push(`    seq = RubySequencer(version=cpu_id, icache=Cache(size='32kB', assoc=2), dcache=Cache(size='64kB', assoc=4))`);
        lines.push(`    cpu.icache_port = seq.in_ports`);
        lines.push(`    cpu.dcache_port = seq.in_ports`);
        lines.push(`    cntrl = L1Cache_Controller(version=cpu_id, sequencer=seq)`);
        lines.push(`    setattr(system, f'cpu_{cpu_id}', cpu)`);
        lines.push(`    return cntrl`);
        lines.push(``);
      } else if (typeKey === 'CPU_O3') {
        lines.push(`def create_cpu_o3_helper(system, cpu_id, binary_path=None):`);
        lines.push(`    """Compute Tile: DerivO3CPU + Sequencer + Ruby L1Cache_Controller"""`);
        lines.push(`    cpu = DerivO3CPU(cpu_id=cpu_id)`);
        lines.push(`    cpu.createInterruptController()`);
        lines.push(`    if binary_path:`);
        lines.push(`        process = Process(cmd=[binary_path])`);
        lines.push(`        cpu.workload = process`);
        lines.push(`        cpu.createThreads()`);
        lines.push(`    seq = RubySequencer(version=cpu_id, icache=Cache(size='32kB', assoc=4), dcache=Cache(size='64kB', assoc=8))`);
        lines.push(`    cpu.icache_port = seq.in_ports`);
        lines.push(`    cpu.dcache_port = seq.in_ports`);
        lines.push(`    cntrl = L1Cache_Controller(version=cpu_id, sequencer=seq)`);
        lines.push(`    setattr(system, f'cpu_o3_{cpu_id}', cpu)`);
        lines.push(`    return cntrl`);
        lines.push(``);
      } else if (typeKey === 'Cache_L1I') {
        lines.push(`def create_cache_l1i_helper(system, version=0):`);
        lines.push(`    """L1 Instruction Cache Tile Controller"""`);
        lines.push(`    return L1Cache_Controller(version=version, is_icache=True)`);
        lines.push(``);
      } else if (typeKey === 'Cache_L1D') {
        lines.push(`def create_cache_l1d_helper(system, version=0):`);
        lines.push(`    """L1 Data Cache Tile Controller"""`);
        lines.push(`    return L1Cache_Controller(version=version, is_dcache=True)`);
        lines.push(``);
      } else if (typeKey === 'Cache_L2') {
        lines.push(`def create_cache_l2_helper(system, version=0):`);
        lines.push(`    """Shared L2 Cache Bank Tile Controller"""`);
        lines.push(`    return L2Cache_Controller(version=version, l2_size='256kB', assoc=8)`);
        lines.push(``);
      } else if (typeKey === 'Directory') {
        lines.push(`def create_directory_helper(system, version=0):`);
        lines.push(`    """Directory Controller Tile"""`);
        lines.push(`    return Directory_Controller(version=version)`);
        lines.push(``);
      } else if (typeKey === 'DRAM_DDR3') {
        lines.push(`def create_dram_ddr3_helper(system, version=0):`);
        lines.push(`    """Directory Tile + DDR3 Memory Controller"""`);
        lines.push(`    dir_cntrl = Directory_Controller(version=version)`);
        lines.push(`    dir_cntrl.memBuffer = MemCtrl(dram=DDR3_1600_8x8())`);
        lines.push(`    return dir_cntrl`);
        lines.push(``);
      } else if (typeKey === 'DRAM_DDR4') {
        lines.push(`def create_dram_ddr4_helper(system, version=0):`);
        lines.push(`    """Directory Tile + DDR4 Memory Controller"""`);
        lines.push(`    dir_cntrl = Directory_Controller(version=version)`);
        lines.push(`    dir_cntrl.memBuffer = MemCtrl(dram=SingleChannelDDR4_2400())`);
        lines.push(`    return dir_cntrl`);
        lines.push(``);
      } else if (typeKey === 'DRAM_HBM2') {
        lines.push(`def create_dram_hbm2_helper(system, version=0):`);
        lines.push(`    """Directory Tile + HBM2 Memory Controller"""`);
        lines.push(`    dir_cntrl = Directory_Controller(version=version)`);
        lines.push(`    dir_cntrl.memBuffer = MemCtrl(dram=HBM2_2000_4H_1x64())`);
        lines.push(`    return dir_cntrl`);
        lines.push(``);
      } else if (typeKey === 'DMA') {
        lines.push(`def create_dma_helper(system, version=0):`);
        lines.push(`    """DMA Controller Tile"""`);
        lines.push(`    dma_seq = DMASequencer(version=version)`);
        lines.push(`    return DMA_Controller(version=version, dma_sequencer=dma_seq)`);
        lines.push(``);
      } else if (typeKey === 'Synthetic_Traffic') {
        lines.push(`def create_synthetic_traffic_helper(system, version=0):`);
        lines.push(`    """Garnet Synthetic Traffic Benchmarking Generator Tile"""`);
        lines.push(`    gen = GarnetSyntheticTraffic(version=version, sim_cycles=1000000, injection_rate=0.1)`);
        lines.push(`    return L1Cache_Controller(version=version, sequencer=gen)`);
        lines.push(``);
      } else {
        // Repeated Custom Template
        lines.push(`def create_${typeKey}_helper(system):`);
        lines.push(`    return CustomGarnetAccelerator()`);
        lines.push(``);
      }
    }
  });

  // Build System Controllers Function
  lines.push(`def build_system_controllers(system, binary_path=${binaryPath ? `'${binaryPath}'` : 'None'}):`);
  lines.push(`    """`);
  lines.push(`    Instantiates configured gem5 endpoints and attaches them to the system.`);
  lines.push(`    Repeated types (>1x) use helper methods; single types (1x) are built inline.`);
  lines.push(`    Returns the ordered list of controllers for Garnet NoC ExtLink mapping.`);
  lines.push(`    """`);
  lines.push(`    controllers = []`);
  lines.push(``);

  const routerIdMap = new Map<string, number>();
  routerNodes.forEach((node, index) => {
    const rId = node.data.routerId !== undefined ? node.data.routerId : index;
    routerIdMap.set(node.id, rId);
  });

  let cpuCounter = 0;
  let versionCounter = 0;
  endpointNodes.forEach((epNode, idx) => {
    const varName = sanitizeVarName(epNode.data.label || `ep_${idx}`);
    const compType: Gem5ComponentType = epNode.data.gem5Component || 'CPU_Timing';
    const typeKey = epNode.data.type === 'template'
      ? (epNode.data.label ? sanitizeVarName(epNode.data.label) : 'custom_template')
      : compType;

    const isRepeated = generatedHelpers.has(typeKey);
    const ver = versionCounter++;

    lines.push(`    # Endpoint ${idx}: ${epNode.data.label} (${isRepeated ? 'Repeated >1x -> Uses Helper' : 'Single 1x -> Inline Tile'})`);

    if (epNode.data.type === 'template') {
      if (epNode.data.templateInstantiationCode?.trim()) {
        const instCode = epNode.data.templateInstantiationCode.trim();
        lines.push(`    ${instCode.replace(/\n/g, '\n    ')}`);
        const match = instCode.match(/^([a-zA-Z0-9_]+)\s*=/);
        const instantiatedVar = match ? match[1] : varName;
        lines.push(`    system.${instantiatedVar} = ${instantiatedVar}`);
        lines.push(`    controllers.append(${instantiatedVar})`);
      } else if (isRepeated) {
        lines.push(`    ${varName} = create_${typeKey}_helper(system)`);
        lines.push(`    system.${varName} = ${varName}`);
        lines.push(`    controllers.append(${varName})`);
      } else {
        lines.push(`    ${varName} = CustomGarnetAccelerator()`);
        lines.push(`    system.${varName} = ${varName}`);
        lines.push(`    controllers.append(${varName})`);
      }
    } else {
      // Standard gem5 Component
      if (isRepeated) {
        // Use factory helper method
        if (compType === 'CPU_Timing') {
          lines.push(`    ${varName} = create_cpu_timing_helper(system, cpu_id=${cpuCounter++}, binary_path=binary_path)`);
        } else if (compType === 'CPU_O3') {
          lines.push(`    ${varName} = create_cpu_o3_helper(system, cpu_id=${cpuCounter++}, binary_path=binary_path)`);
        } else if (compType === 'Cache_L1I') {
          lines.push(`    ${varName} = create_cache_l1i_helper(system, version=${ver})`);
        } else if (compType === 'Cache_L1D') {
          lines.push(`    ${varName} = create_cache_l1d_helper(system, version=${ver})`);
        } else if (compType === 'Cache_L2') {
          lines.push(`    ${varName} = create_cache_l2_helper(system, version=${ver})`);
        } else if (compType === 'Directory') {
          lines.push(`    ${varName} = create_directory_helper(system, version=${ver})`);
        } else if (compType === 'DRAM_DDR3') {
          lines.push(`    ${varName} = create_dram_ddr3_helper(system, version=${ver})`);
        } else if (compType === 'DRAM_DDR4') {
          lines.push(`    ${varName} = create_dram_ddr4_helper(system, version=${ver})`);
        } else if (compType === 'DRAM_HBM2') {
          lines.push(`    ${varName} = create_dram_hbm2_helper(system, version=${ver})`);
        } else if (compType === 'DMA') {
          lines.push(`    ${varName} = create_dma_helper(system, version=${ver})`);
        } else if (compType === 'Synthetic_Traffic') {
          lines.push(`    ${varName} = create_synthetic_traffic_helper(system, version=${ver})`);
        } else {
          lines.push(`    ${varName} = create_${typeKey}_helper(system)`);
        }
      } else {
        // Used ONLY 1x -> Inline instantiation
        switch (compType) {
          case 'CPU_Timing': {
            const cid = cpuCounter++;
            lines.push(`    ${varName}_cpu = TimingSimpleCPU(cpu_id=${cid})`);
            lines.push(`    ${varName}_cpu.createInterruptController()`);
            lines.push(`    if binary_path:`);
            lines.push(`        ${varName}_cpu.workload = Process(cmd=[binary_path])`);
            lines.push(`        ${varName}_cpu.createThreads()`);
            lines.push(`    ${varName}_seq = RubySequencer(version=${cid}, icache=Cache(size='32kB', assoc=2), dcache=Cache(size='64kB', assoc=4))`);
            lines.push(`    ${varName}_cpu.icache_port = ${varName}_seq.in_ports`);
            lines.push(`    ${varName}_cpu.dcache_port = ${varName}_seq.in_ports`);
            lines.push(`    system.${varName}_cpu = ${varName}_cpu`);
            lines.push(`    ${varName} = L1Cache_Controller(version=${cid}, sequencer=${varName}_seq)`);
            break;
          }
          case 'CPU_O3': {
            const cid = cpuCounter++;
            lines.push(`    ${varName}_cpu = DerivO3CPU(cpu_id=${cid})`);
            lines.push(`    ${varName}_cpu.createInterruptController()`);
            lines.push(`    if binary_path:`);
            lines.push(`        ${varName}_cpu.workload = Process(cmd=[binary_path])`);
            lines.push(`        ${varName}_cpu.createThreads()`);
            lines.push(`    ${varName}_seq = RubySequencer(version=${cid}, icache=Cache(size='32kB', assoc=4), dcache=Cache(size='64kB', assoc=8))`);
            lines.push(`    ${varName}_cpu.icache_port = ${varName}_seq.in_ports`);
            lines.push(`    ${varName}_cpu.dcache_port = ${varName}_seq.in_ports`);
            lines.push(`    system.${varName}_cpu = ${varName}_cpu`);
            lines.push(`    ${varName} = L1Cache_Controller(version=${cid}, sequencer=${varName}_seq)`);
            break;
          }
          case 'Cache_L1I':
            lines.push(`    ${varName} = L1Cache_Controller(version=${ver}, is_icache=True)`);
            break;
          case 'Cache_L1D':
            lines.push(`    ${varName} = L1Cache_Controller(version=${ver}, is_dcache=True)`);
            break;
          case 'Cache_L2':
            lines.push(`    ${varName} = L2Cache_Controller(version=${ver}, l2_size='256kB', assoc=8)`);
            break;
          case 'Directory':
            lines.push(`    ${varName} = Directory_Controller(version=${ver})`);
            break;
          case 'DRAM_DDR3':
            lines.push(`    ${varName} = Directory_Controller(version=${ver})`);
            lines.push(`    ${varName}.memBuffer = MemCtrl(dram=DDR3_1600_8x8())`);
            break;
          case 'DRAM_DDR4':
            lines.push(`    ${varName} = Directory_Controller(version=${ver})`);
            lines.push(`    ${varName}.memBuffer = MemCtrl(dram=SingleChannelDDR4_2400())`);
            break;
          case 'DRAM_HBM2':
            lines.push(`    ${varName} = Directory_Controller(version=${ver})`);
            lines.push(`    ${varName}.memBuffer = MemCtrl(dram=HBM2_2000_4H_1x64())`);
            break;
          case 'DMA':
            lines.push(`    ${varName}_seq = DMASequencer(version=${ver})`);
            lines.push(`    ${varName} = DMA_Controller(version=${ver}, dma_sequencer=${varName}_seq)`);
            break;
          case 'Synthetic_Traffic':
            lines.push(`    ${varName}_gen = GarnetSyntheticTraffic(version=${ver}, sim_cycles=1000000, injection_rate=0.1)`);
            lines.push(`    ${varName} = L1Cache_Controller(version=${ver}, sequencer=${varName}_gen)`);
            break;
          case 'Custom_Accelerator':
          default:
            lines.push(`    ${varName} = CustomGarnetAccelerator()`);
            break;
        }
      }
      lines.push(`    system.${varName} = ${varName}`);
      lines.push(`    controllers.append(${varName})`);
    }
    lines.push(``);
  });

  lines.push(`    return controllers`);
  lines.push(``);

  // 5. Garnet Topology Definition Class
  lines.push(`# ==============================================================================`);
  lines.push(`# SECTION 3: GARNET NOC TOPOLOGY DEFINITION`);
  lines.push(`# ==============================================================================`);
  lines.push(``);
  lines.push(`class Garnet${sanitizeClassName(project.name)}Topology(BaseTopology):`);
  lines.push(`    """`);
  lines.push(`    Autogenerated Garnet NoC Topology Class.`);
  lines.push(`    Contains ${routerNodes.length} Routers and ${endpointNodes.length} Endpoints.`);
  lines.push(`    """`);
  lines.push(`    def __init__(self, controllers):`);
  lines.push(`        super().__init__(controllers)`);
  lines.push(``);
  lines.push(`    def makeTopology(self, options, network, IntLink, ExtLink, Router):`);
  lines.push(`        nodes = self.nodes`);
  lines.push(``);

  // Instantiate Routers
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        # Instantiate NoC Routers`);
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        routers = []`);
  routerNodes.forEach((rNode) => {
    const rId = routerIdMap.get(rNode.id);
    const latency = rNode.data.latency || 1;
    lines.push(`        routers.append(Router(router_id=${rId}, latency=${latency}))  # Node: ${rNode.data.label}`);
  });
  lines.push(`        network.routers = routers`);
  lines.push(``);

  // Internal Links (Router -> Router)
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        # Internal Links (Router to Router)`);
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        int_links = []`);
  let linkCounter = 0;

  project.links.forEach((link) => {
    const srcIsRouter = routerIdMap.has(link.source);
    const dstIsRouter = routerIdMap.has(link.target);

    if (srcIsRouter && dstIsRouter) {
      const srcRouterId = routerIdMap.get(link.source);
      const dstRouterId = routerIdMap.get(link.target);
      const latency = link.latency || 1;
      const weight = link.weight || 1;
      const bwBytes = Math.max(1, Math.floor((link.bandwidth || 128) / 8));

      // Forward link
      lines.push(
        `        int_links.append(IntLink(link_id=${linkCounter++}, src_node=routers[${srcRouterId}], dst_node=routers[${dstRouterId}], latency=${latency}, weight=${weight}, width=${bwBytes}))`
      );

      // Bidirectional link
      if (link.direction === 'bi') {
        lines.push(
          `        int_links.append(IntLink(link_id=${linkCounter++}, src_node=routers[${dstRouterId}], dst_node=routers[${srcRouterId}], latency=${latency}, weight=${weight}, width=${bwBytes}))`
        );
      }
    }
  });

  lines.push(`        network.int_links = int_links`);
  lines.push(``);

  // External Links (Endpoints -> Routers)
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        # External Links (Endpoints & Controllers to Routers)`);
  lines.push(`        # ----------------------------------------------------------------------`);
  lines.push(`        ext_links = []`);
  let extLinkCounter = 0;

  endpointNodes.forEach((epNode, idx) => {
    const connectedLink = project.links.find(
      (l) => (l.source === epNode.id && routerIdMap.has(l.target)) || (l.target === epNode.id && routerIdMap.has(l.source))
    );

    const routerId = connectedLink
      ? routerIdMap.get(connectedLink.source === epNode.id ? connectedLink.target : connectedLink.source)
      : 0;

    const label = epNode.data.label || `Endpoint_${idx}`;
    const latency = connectedLink ? connectedLink.latency : 1;
    const bwBytes = connectedLink ? Math.max(1, Math.floor((connectedLink.bandwidth || 128) / 8)) : 16;

    lines.push(`        # ExtLink ${extLinkCounter}: ${label} -> Router ${routerId}`);
    lines.push(
      `        ext_links.append(ExtLink(link_id=${extLinkCounter++}, extnode=nodes[${idx}], intnode=routers[${routerId}], latency=${latency}, width=${bwBytes}))`
    );
  });

  lines.push(`        network.ext_links = ext_links`);
  lines.push(``);

  // 6. Full Standalone System Runner Block
  lines.push(`# ==============================================================================`);
  lines.push(`# SECTION 4: FULL SYSTEM SIMULATION BENCHMARK RUNNER`);
  lines.push(`# Direct execution script for gem5 simulation environment`);
  lines.push(`# ==============================================================================`);
  lines.push(``);
  lines.push(`def build_and_run_system():`);
  lines.push(`    """`);
  lines.push(`    Builds the top-level gem5 System, instantiates controllers, Garnet NoC,`);
  lines.push(`    and executes the simulation.`);
  lines.push(`    """`);
  lines.push(`    system = System()`);
  lines.push(`    system.clk_domain = SrcClockDomain(clock='${project.settings.clockDomain || '2GHz'}', voltage_domain=VoltageDomain())`);
  lines.push(`    system.mem_mode = 'timing'`);
  lines.push(`    system.mem_ranges = [AddrRange('512MB')]`);
  lines.push(``);
  lines.push(`    # 1. Build and attach all configured CPUs, Caches, DRAM, and Custom Endpoints`);
  lines.push(`    controllers = build_system_controllers(system, binary_path=${binaryPath ? `'${binaryPath}'` : 'None'})`);
  lines.push(``);
  lines.push(`    # 2. Build Garnet NoC Network`);
  lines.push(`    network = GarnetNetwork(`);
  lines.push(`        ruby_system=system,`);
  lines.push(`        vcs_per_vnet=${project.settings.buffersPerVC || 4},`);
  lines.push(`        buffers_per_data_vc=${project.settings.buffersPerVC || 4},`);
  lines.push(`        buffers_per_ctrl_vc=${project.settings.buffersPerVC || 4},`);
  lines.push(`        ni_single_vnet_buffer=${project.settings.niSingleVnetBuffer ? 'True' : 'False'},`);
  lines.push(`        routing_algorithm=${project.settings.routingAlgorithm === 'xy' ? 1 : 0}`);
  lines.push(`    )`);
  lines.push(`    topology = Garnet${sanitizeClassName(project.name)}Topology(controllers)`);
  lines.push(`    topology.makeTopology(None, network, IntLink, ExtLink, Router)`);
  lines.push(`    network.init_net()`);
  lines.push(``);
  lines.push(`    # 3. Connect Memory & CPU Ports`);
  lines.push(`    system.system_port = system.membus.cpu_side_ports if hasattr(system, 'membus') else None`);
  lines.push(``);
  lines.push(`    # 4. Instantiate Root & Run gem5 Simulation`);
  lines.push(`    root = Root(full_system=False, system=system)`);
  lines.push(`    m5.instantiate()`);
  lines.push(`    print("==================================================================")`);
  lines.push(`    print("Beginning gem5 Garnet NoC simulation: ${project.name}")`);
  lines.push(`    print("Routers: ${routerNodes.length} | Endpoints: ${endpointNodes.length} | Links: ${project.links.length}")`);
  lines.push(`    if ${binaryPath ? `'${binaryPath}'` : 'None'}:`);
  lines.push(`        print(f"Workload Binary: {${binaryPath ? `'${binaryPath}'` : 'None'}}")`);
  lines.push(`    print("==================================================================")`);
  lines.push(`    exit_event = m5.simulate()`);
  lines.push(`    print(f"Simulation finished @ tick {m5.curTick()} because: {exit_event.getCause()}")`);
  lines.push(``);

  lines.push(`if __name__ == '__main__':`);
  lines.push(`    build_and_run_system()`);

  return lines.join('\n');
}

function sanitizeClassName(str: string): string {
  return str.replace(/[^a-zA-Z0-9]/g, '');
}

function sanitizeVarName(str: string): string {
  const sanitized = str.toLowerCase().replace(/[^a-z0-9_]/g, '_');
  return /^[a-z_]/.test(sanitized) ? sanitized : `var_${sanitized}`;
}
